[package]
name = "samaku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10.0", features = ["lazy", "image", "advanced", "smol"] }
rustsynth-sys = { version = "0.4.0", features = ["vapoursynth-functions", "vsscript-functions"] }
libass-sys = { version = "0.1.0", path = "libass-sys" }
once_cell = "1.18.0"
rfd = "0.12.0"
smol = "1.3.0"
