[package]
name = "samaku"
version = "0.1.0"
edition = "2024"
rust-version = "1.89"
description = "Node-based editor for typesetting of ASS subtitles"
repository = "https://github.com/meew0/samaku"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["ass", "subtitle"]
categories = ["multimedia"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.13.1", features = [
    "lazy",
    "image",
    "advanced",
    "smol",
    "svg",
] }
iced_aw = { version = "0.12.0", features = ["menu", "selection_list"] }
iced_fonts = { version = "0.2.1", features = ["bootstrap"] }
iced_table = { git = "https://github.com/meew0/iced_table.git", rev = "aa3d3cc1713de3f2a5301ab575e6b632e48b6765" }
iced_node_editor = { git = "https://github.com/meew0/iced-node-editor.git", rev = "3ab7671ed8155d34afc5a5485a66b7a7cd9d05f5" }
rustsynth-sys = { version = "0.5.0", features = [
    "vapoursynth-functions",
    "vsscript-functions",
] }
libass-sys = { version = "0.1.0", path = "libass-sys" }
bestsource-sys = { version = "0.1.0", path = "bestsource-sys" }
libmv-capi-sys = { git = "https://github.com/meew0/libmv-capi-sys.git" }
matroska-demuxer = "0.7"
rfd = "0.15.4"
smol = "2.0"
cpal = "0.16"
libc = "0.2.175"
fast-float2 = "0.2"
thiserror = "2.0"
anyhow = "1.0"
inventory = "0.3.21"
regex = "1.11"
interavl = "0.3"
indexmap = "2.11"
serde = "1.0.219"
typetag = "0.2.20"
ciborium = "0.2.2"
data-encoding = "2.9"
miniz_oxide = "0.8.9"
data-encoding-macro = "0.1.18"
vsprintf = "2.0.0"
static_assertions = "1.1.0"

[dev-dependencies]
assert_matches2 = "0.1.2"
criterion = "0.7"
rand = "0.9"
rand_pcg = "0.9"

[[bench]]
name = "main"
harness = false

[profile.bench]
opt-level = 3
debug = 2
debug-assertions = false
lto = "thin"
codegen-units = 1
