[package]
name = "samaku"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.10.0", features = ["lazy", "image", "advanced", "smol", "svg"] }
iced_aw = { version = "0.7.0", features = ["menu", "selection_list"] }
iced_table = "0.1"
iced_node_editor = { git = "https://github.com/meew0/iced-node-editor.git", branch = "sockets" }
#iced_node_editor = { path = "../iced-node-editor/iced_node_editor" }
rustsynth-sys = { version = "0.4.0", features = ["vapoursynth-functions", "vsscript-functions"] }
libass-sys = { version = "0.1.0", path = "libass-sys" }
bestsource-sys = { version = "0.1.0", path = "bestsource-sys" }
libmv-capi-sys = { git = "https://github.com/meew0/libmv-capi-sys.git" }
once_cell = "1.18.0"
rfd = "0.12.0"
smol = "1.3.0"
cpal = "0.15"
libc = "0.2.148"
fast-float = "0.2"
thiserror = "1.0"
inventory = "0.3.12"
regex = "1.10.1"
serde = "1.0.189"
typetag = "0.2.13"
ciborium = "0.2.1"
data-encoding = "2.4.0"
miniz_oxide = "0.7.1"

[dev-dependencies]
assert_matches2 = "0.1"
criterion = "0.5"

[[bench]]
name = "nde"
harness = false
