[package]
name = "samaku"
version = "0.1.0"
edition = "2021"
rust-version = "1.81"
description = "Node-based editor for typesetting of ASS subtitles"
repository = "https://github.com/meew0/samaku"
readme = "README.md"
license = "GPL-3.0-or-later"
keywords = ["ass", "subtitle"]
categories = ["multimedia"]
publish = false

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced = { version = "0.12.1", features = [
    "lazy",
    "image",
    "advanced",
    "smol",
    "svg",
] }
iced_aw = { version = "0.9.3", features = ["menu", "selection_list", "icons"] }
iced_table = { git = "https://github.com/meew0/iced_table.git" }
iced_node_editor = { git = "https://github.com/meew0/iced-node-editor.git", branch = "sockets-iced-v0.12" }
rustsynth-sys = { version = "0.4.0", features = [
    "vapoursynth-functions",
    "vsscript-functions",
] }
libass-sys = { version = "0.1.0", path = "libass-sys" }
bestsource-sys = { version = "0.1.0", path = "bestsource-sys" }
libmv-capi-sys = { git = "https://github.com/meew0/libmv-capi-sys.git" }
rfd = "0.14"
smol = "2.0"
cpal = "0.15"
libc = "0.2.158"
fast-float = "0.2"
thiserror = "1.0"
inventory = "0.3.15"
regex = "1.10"
serde = "1.0.210"
typetag = "0.2.18"
ciborium = "0.2.2"
data-encoding = "2.6"
miniz_oxide = "0.8.0"
data-encoding-macro = "0.1.15"
vsprintf = "2.0.0"
static_assertions = "1.1.0"

[dev-dependencies]
assert_matches2 = "0.1.2"
criterion = "0.5.1"

[[bench]]
name = "nde"
harness = false
