#!/bin/sh

cargo test
err1=$?
cargo fmt --check
err2=$?
cargo clippy
err3=$?

set -e

if [ $err1 -ne 0 ] || [ $err2 -ne 0 ] || [ $err3 -ne 0 ]; then
    echo "Pre-commit hook failed!"
    exit 1
else
    exit 0
fi
